[package]
name = "rusttype"
version = "0.2.1"
authors = ["Dylan Ede <dylanede@googlemail.com>"]
description = """
A pure Rust alternative to libraries like FreeType.

RustType provides an API for loading, querying and rasterising TrueType fonts.

It also provides an implementation of a dynamic GPU glyph cache for hardware font rendering.
"""
documentation = "https://dylanede.github.io/rusttype"
homepage = "https://github.com/dylanede/rusttype"
repository = "https://github.com/dylanede/rusttype"
readme = "README.md"
license = "MIT / Apache-2.0"
keywords = ["font", "truetype", "opentype", "ttf", "otf"]
exclude = ["examples/*.ttf"]

[dependencies]
arrayvec = "^0.3.13"
stb_truetype = "^0.2"

[dev-dependencies]
glium = "^0.14"
unicode-normalization = "^0.1.2"
